### PR TITLE
Ft implement feedback 164795546

### PR DESCRIPTION
**Pull request by ernesthenry**
*What does this PR do?*
- Validates user input
- Adds navigation from registration page to login page
- Adds the threading concept to the messages in the inbox
-Add buttons for retracting sent messages
-Removes edit buttons on sent messages
-Adds match password validations when the user resets their password
*Description of tasks completed*
I validated password fields using regular expressions
I used HTML5 validations for missing user inputs
-Used collapsible buttons for threading
-Removed edit buttons on both received and sent messages
Added buttons for retracting sent messages
-Added navigation from the registration page back to the login
*Screenshots*
regist
snipp
*How to manually test this*
https://github.com/ernesthenry/EPIC-MAIL/UI/index.html
*Relevant pivotal tracker stories* 
 - [#164795546](https://www.pivotaltracker.com/story/show/164795546)

### CODE REVIEW

**Comment by Estaer** [comment]
The link that you attached to `How to manually test` is invalid. Kindly check it out.

**Comment by HabibSentongo** [comment]
your color scheme looks great 'basing on the screenshot', please provide the right gh-pages link so we can manually test the page as @Estaer already mentioned

**Comment by ernesthenry** [comment]
https://ernesthenry.github.io/EPIC-MAIL/UI/index.html
That's the link

**Comment by HabibSentongo** [comment]
Your interface looks great and you have nice data validations. Keep it up

**Pull request merged**
